steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-f'
  - 'cloud-run/Dockerfile'
  - '-t'
  - 'us-central1-docker.pkg.dev/ttb-lang1/cloud-run-source-deploy/technical-analysis-mcp:$SHORT_SHA'
  - '.'
images:
- 'us-central1-docker.pkg.dev/ttb-lang1/cloud-run-source-deploy/technical-analysis-mcp:$SHORT_SHA'
