"""Sector mapping for equities."""

# S&P 500 stock to sector mapping
SECTOR_MAPPING = {
    # Technology
    "AAPL": "Technology",
    "MSFT": "Technology",
    "NVDA": "Technology",
    "GOOGL": "Technology",
    "GOOG": "Technology",
    "META": "Technology",
    "AMZN": "Technology",
    "TSLA": "Technology",
    "NFLX": "Technology",
    "ADBE": "Technology",
    "CSCO": "Technology",
    "INTC": "Technology",
    "AMD": "Technology",
    "CRM": "Technology",
    "ORACLE": "Technology",
    "IBM": "Technology",
    "ACN": "Technology",
    "QCOM": "Technology",
    "AVGO": "Technology",
    "MU": "Technology",
    "AMAT": "Technology",
    "ASML": "Technology",
    "LRCX": "Technology",
    "SNPS": "Technology",
    "CDNS": "Technology",
    "WDAY": "Technology",
    "OKTA": "Technology",
    "NOW": "Technology",
    "CRWD": "Technology",
    "NET": "Technology",
    # Healthcare
    "JNJ": "Healthcare",
    "UNH": "Healthcare",
    "PFE": "Healthcare",
    "ABBV": "Healthcare",
    "TMO": "Healthcare",
    "MRNA": "Healthcare",
    "LLY": "Healthcare",
    "MRK": "Healthcare",
    "AMGN": "Healthcare",
    "GILD": "Healthcare",
    "BIIB": "Healthcare",
    "ANTM": "Healthcare",
    "CI": "Healthcare",
    "HUM": "Healthcare",
    "REGN": "Healthcare",
    "ILMN": "Healthcare",
    "VRTX": "Healthcare",
    "EXAS": "Healthcare",
    "ZTS": "Healthcare",
    "SYK": "Healthcare",
    "DXCM": "Healthcare",
    "ELV": "Healthcare",
    # Financials
    "JPM": "Financials",
    "BAC": "Financials",
    "WFC": "Financials",
    "GS": "Financials",
    "MS": "Financials",
    "BLK": "Financials",
    "AXP": "Financials",
    "V": "Financials",
    "MA": "Financials",
    "DFS": "Financials",
    "COF": "Financials",
    "AIG": "Financials",
    "PNC": "Financials",
    "USB": "Financials",
    "TFC": "Financials",
    "KEY": "Financials",
    "CME": "Financials",
    "ICE": "Financials",
    "PYPL": "Financials",
    "SQ": "Financials",
    # Consumer Discretionary
    "AMZN": "Consumer Discretionary",
    "TSLA": "Consumer Discretionary",
    "MCD": "Consumer Discretionary",
    "NKE": "Consumer Discretionary",
    "DIDI": "Consumer Discretionary",
    "LVMh": "Consumer Discretionary",
    "RCL": "Consumer Discretionary",
    "CCL": "Consumer Discretionary",
    "UAL": "Consumer Discretionary",
    "AAL": "Consumer Discretionary",
    "DAL": "Consumer Discretionary",
    "GM": "Consumer Discretionary",
    "F": "Consumer Discretionary",
    "TM": "Consumer Discretionary",
    "HWM": "Consumer Discretionary",
    # Consumer Staples
    "KO": "Consumer Staples",
    "PEP": "Consumer Staples",
    "WMT": "Consumer Staples",
    "CL": "Consumer Staples",
    "KMB": "Consumer Staples",
    "MO": "Consumer Staples",
    "PM": "Consumer Staples",
    "GIS": "Consumer Staples",
    "HSY": "Consumer Staples",
    "K": "Consumer Staples",
    "STZ": "Consumer Staples",
    "PG": "Consumer Staples",
    # Industrials
    "BA": "Industrials",
    "CAT": "Industrials",
    "LMT": "Industrials",
    "RTX": "Industrials",
    "GE": "Industrials",
    "MMM": "Industrials",
    "HON": "Industrials",
    "ITW": "Industrials",
    "PCAR": "Industrials",
    "NSC": "Industrials",
    "CSX": "Industrials",
    "UNP": "Industrials",
    "KSU": "Industrials",
    # Energy
    "XOM": "Energy",
    "CVX": "Energy",
    "COP": "Energy",
    "EOG": "Energy",
    "SLB": "Energy",
    "MPC": "Energy",
    "VLO": "Energy",
    "PSX": "Energy",
    "HAL": "Energy",
    "OKE": "Energy",
    "KMI": "Energy",
    "TPL": "Energy",
    # Utilities
    "NEE": "Utilities",
    "DUK": "Utilities",
    "SO": "Utilities",
    "D": "Utilities",
    "AEP": "Utilities",
    "EXC": "Utilities",
    "XEL": "Utilities",
    "PPL": "Utilities",
    "AWK": "Utilities",
    "WEC": "Utilities",
    # Real Estate
    "PLD": "Real Estate",
    "AMT": "Real Estate",
    "DLR": "Real Estate",
    "EQIX": "Real Estate",
    "AVB": "Real Estate",
    "EQR": "Real Estate",
    "PSA": "Real Estate",
    "SPG": "Real Estate",
    "WY": "Real Estate",
    "URI": "Real Estate",
    # Materials
    "APD": "Materials",
    "LIN": "Materials",
    "NEM": "Materials",
    "FCX": "Materials",
    "DD": "Materials",
    "CTVA": "Materials",
    "ALB": "Materials",
    "SHW": "Materials",
    "STLD": "Materials",
    "X": "Materials",
    # Communication Services
    "META": "Communication Services",
    "GOOGL": "Communication Services",
    "GOOG": "Communication Services",
    "NFLX": "Communication Services",
    "CMCSA": "Communication Services",
    "CHTR": "Communication Services",
    "NWSA": "Communication Services",
    "NWS": "Communication Services",
    "FOXA": "Communication Services",
    "FOX": "Communication Services",
}


def get_sector(symbol: str) -> str:
    """Get sector for a given symbol.

    Args:
        symbol: Ticker symbol.

    Returns:
        Sector name, or "Other" if not found.
    """
    return SECTOR_MAPPING.get(symbol.upper(), "Other")
